### ISSUE TITLE
New and unsaved files should use the first available workspace

### ISSUE THREAD

**Issue by tomaciazek** [ansible/ansible-language-server#160] opened 2021-11-30 18:02 UTC
### Problem

Currently, if a new (unsaved) file tab is opened only basic syntax highlighting is provided.

### Solution

If the user has at least one workspace open (and most run with just one), we could take such workspace (the first root folder) and use it as the context for the unsaved file.

**Comment by ssbarnea** [comment] 2022-06-18 10:25
Duplicate of #159

**Closed by ssbarnea** 2022-06-18 10:25 UTC
Labels: enhancement, new
